### ISSUE TITLE
Trojan?

### ISSUE THREAD

**Issue by SpamsAlex** [quickfs/quickfs-excel-addin#2]
Hi, 

When I try to upload the file I have a message from my AV saying there is a trojan in the file.

Regards, 

Alex

**Comment by quickfs** [comment]
This is a persistent problem that seems to crop up whenever AV providers push out a major update. We resubmit false positive reports every few months and are always whitelisted after disputing. The AV providers seem to flag Excel macros as a generic threat vector, so I'm not sure that there's anything that can be done to permanently avoid the problem.

I re-checked Kaspersky today and it marks quickfs.install.xlam as clean: https://opentip.kaspersky.com/DD2BE4F7CD099E16201F09FFF61C4311D23202ECA2C7A631D02CFDE7A513CA35/

---------- Forwarded message ---------
From: Kaspersky AntiVirus Lab <newvirus@kaspersky.com>
Date: Mon, Jun 14, 2021 at 11:50 PM
Subject: RE: Kaspersky Anti-virus Lab replies to your request [VD3] [FILE:2] [KL-1053192]
To: tcooper@quickfs.net <tcooper@quickfs.net>


Hello,

Sorry, it was a false detection. It will be fixed.
Thank you for your help.

Best regards, Maxim Starodubov, Malware analyst, Kaspersky Lab
39A/3 Leningradskoe Shosse, Moscow, 125212, Russia Tel./Fax: + 7 (495) 797 8700 http://www.kaspersky.com https://securelist.com
https://opentip.kaspersky.com/ - get insights about suspicious files, hashes, URLs, IP addresses or domain names

__________________________________________

From:   tcooper@quickfs.net
Received:       6/14/2021 11:29:39 PM (UTC)
Sent:   6/14/2021 11:29:38 PM (UTC)
To:     newvirus@kaspersky.com
Subject:        Kaspersky Anti-virus Lab replies to your request [VD3] [FILE:2]

Client feedback, query DD2BE4F7CD099E16201F09FFF61C4311D23202ECA2C7A631D02CFDE7A513CA35, type [Hash], zone [Red], was sent with the following commentary:
Some of our customers that use Kaspersky are worried that a legitimate tool offered by QuickFS.net is a virus. The Excel add-in that they're using is completely harmless. The code for the add-in is published for anyone to review and allows users to import stock quotes and data into a spreadsheet. The code for the add-in is published here: https://github.com/quickfs/quickfs-excel-addin The add-in can be downloaded from here: https://quickfs.net/using-the-excel-add-in The add-in makes requests to our API based on the user's Excel formulas: api.quickfs.net beta.quickfs.net The Trojan that's flagged by Kaspersky is: HEUR:Trojan-Downloader.MSOffice.SLoad.gen Please let me know how we can correct this issue. Cheers, Ted Cooper Founder, QuickFS.net tcooper@quickfs.net.

This message is generated automatically by OpenTIP.
With Best regards,
OpenTIP Team.
